# Generated by Django 5.1.1 on 2024-09-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_comment_title_alter_comment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='media/courses/default_course.jpg', upload_to='courses/'),
        ),
    ]
