# Generated by Django 5.1.1 on 2024-09-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='courses/default_course.jpg', upload_to='courses/'),
        ),
    ]
