# Generated by Django 5.1.1 on 2024-09-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_comment_user_comment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='courses/default_user.jpg', upload_to='customers/'),
        ),
    ]
