# Generated by Django 5.1.1 on 2024-09-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='default_user.jpg', upload_to='customers/'),
        ),
    ]
