# Generated by Django 5.1.1 on 2024-09-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default='teachers/default_teacher.png', upload_to='teachers/'),
        ),
    ]
