# Generated by Django 5.1.1 on 2024-09-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
